# Generated by Django 4.2.26 on 2025-11-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for recurring sessions (0=Monday, 6=Sunday)')),
                ('time', models.TimeField(help_text='Time of day for the session')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('start_date', models.DateField(help_text='First date this pattern is active')),
                ('end_date', models.DateField(blank=True, help_text='Last date this pattern is active (null = no end date)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['weekday', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('is_exception', models.BooleanField(default=False, help_text='True if this occurrence was modified from its pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurrence_pattern', models.ForeignKey(blank=True, help_text='Parent pattern for recurring sessions (null for one-time sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='booking_sessions.recurrencepattern')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='recurrencepattern',
            index=models.Index(fields=['is_active', 'weekday'], name='booking_ses_is_acti_3cac9c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencepattern',
            index=models.Index(fields=['start_date', 'end_date'], name='booking_ses_start_d_e3a01a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['start_datetime', 'status'], name='booking_ses_start_d_e2f82b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['recurrence_pattern', 'start_datetime'], name='booking_ses_recurre_140636_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['status'], name='booking_ses_status_144511_idx'),
        ),
    ]
