# Generated by Django 4.2.26 on 2025-11-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('session_type', models.CharField(choices=[('one_time', 'One-time Session'), ('recurring', 'Recurring Weekly Session')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('recurrence_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for recurring sessions (0=Monday, 6=Sunday)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SessionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField(help_text='The date of the occurrence being modified/cancelled')),
                ('is_cancelled', models.BooleanField(default=False, help_text='If True, this occurrence is cancelled')),
                ('modified_datetime', models.DateTimeField(blank=True, help_text='If set, this occurrence is moved to this datetime', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='booking_sessions.session')),
            ],
            options={
                'ordering': ['exception_date'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type', 'start_datetime'], name='booking_ses_session_5d670e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['recurrence_day'], name='booking_ses_recurre_3c9bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionexception',
            index=models.Index(fields=['session', 'exception_date'], name='booking_ses_session_66b51a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexception',
            unique_together={('session', 'exception_date')},
        ),
    ]
